/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ConversationId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CallType = IDL.Variant({
  'stream' : IDL.Null,
  'audio' : IDL.Null,
  'webcam' : IDL.Null,
});
export const Username = IDL.Text;
export const CallLogEntry = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Nat,
  'callType' : CallType,
  'toUser' : IDL.Opt(Username),
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
  'fromUser' : IDL.Opt(Username),
});
export const DisplayName = IDL.Text;
export const UserProfile = IDL.Record({
  'username' : Username,
  'displayName' : DisplayName,
});
export const Message = IDL.Record({
  'messageId' : IDL.Nat,
  'text' : IDL.Text,
  'sender' : IDL.Principal,
  'conversationId' : ConversationId,
  'timestamp' : IDL.Int,
});
export const DirectoryUserResult = IDL.Record({
  'principal' : IDL.Principal,
  'username' : Username,
  'displayName' : DisplayName,
});
export const MessageRequest = IDL.Record({
  'text' : IDL.Text,
  'sender' : IDL.Principal,
  'conversationId' : ConversationId,
});
export const MessageReply = IDL.Record({
  'messageId' : IDL.Nat,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addConversation' : IDL.Func([ConversationId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteCallEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteMessage' : IDL.Func([ConversationId, IDL.Nat], [], []),
  'getCallHistory' : IDL.Func([], [IDL.Vec(CallLogEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserConversations' : IDL.Func([], [IDL.Vec(ConversationId)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasConversation' : IDL.Func([ConversationId], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMessages' : IDL.Func([ConversationId], [IDL.Vec(Message)], ['query']),
  'recordCall' : IDL.Func(
      [IDL.Opt(Username), IDL.Opt(Username), CallType, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'removeConversation' : IDL.Func([ConversationId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchDirectoryUsers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DirectoryUserResult)],
      ['query'],
    ),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
  'sendMessage' : IDL.Func([MessageRequest], [MessageReply], []),
  'updateProfile' : IDL.Func([IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ConversationId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CallType = IDL.Variant({
    'stream' : IDL.Null,
    'audio' : IDL.Null,
    'webcam' : IDL.Null,
  });
  const Username = IDL.Text;
  const CallLogEntry = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Nat,
    'callType' : CallType,
    'toUser' : IDL.Opt(Username),
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
    'fromUser' : IDL.Opt(Username),
  });
  const DisplayName = IDL.Text;
  const UserProfile = IDL.Record({
    'username' : Username,
    'displayName' : DisplayName,
  });
  const Message = IDL.Record({
    'messageId' : IDL.Nat,
    'text' : IDL.Text,
    'sender' : IDL.Principal,
    'conversationId' : ConversationId,
    'timestamp' : IDL.Int,
  });
  const DirectoryUserResult = IDL.Record({
    'principal' : IDL.Principal,
    'username' : Username,
    'displayName' : DisplayName,
  });
  const MessageRequest = IDL.Record({
    'text' : IDL.Text,
    'sender' : IDL.Principal,
    'conversationId' : ConversationId,
  });
  const MessageReply = IDL.Record({
    'messageId' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addConversation' : IDL.Func([ConversationId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteCallEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteMessage' : IDL.Func([ConversationId, IDL.Nat], [], []),
    'getCallHistory' : IDL.Func([], [IDL.Vec(CallLogEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserConversations' : IDL.Func([], [IDL.Vec(ConversationId)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasConversation' : IDL.Func([ConversationId], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMessages' : IDL.Func([ConversationId], [IDL.Vec(Message)], ['query']),
    'recordCall' : IDL.Func(
        [IDL.Opt(Username), IDL.Opt(Username), CallType, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'removeConversation' : IDL.Func([ConversationId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchDirectoryUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DirectoryUserResult)],
        ['query'],
      ),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
    'sendMessage' : IDL.Func([MessageRequest], [MessageReply], []),
    'updateProfile' : IDL.Func([IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };