/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CallLogEntry {
  'id' : bigint,
  'duration' : bigint,
  'callType' : CallType,
  'toUser' : [] | [Username],
  'notes' : string,
  'timestamp' : bigint,
  'fromUser' : [] | [Username],
}
export type CallType = { 'stream' : null } |
  { 'audio' : null } |
  { 'webcam' : null };
export type ConversationId = string;
export type DisplayName = string;
export interface Message {
  'messageId' : bigint,
  'text' : string,
  'sender' : Principal,
  'conversationId' : ConversationId,
  'timestamp' : bigint,
}
export interface MessageReply { 'messageId' : bigint, 'timestamp' : bigint }
export interface MessageRequest {
  'text' : string,
  'sender' : Principal,
  'conversationId' : ConversationId,
}
export interface UserProfile {
  'username' : Username,
  'displayName' : DisplayName,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Username = string;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addConversation' : ActorMethod<[ConversationId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createUserProfile' : ActorMethod<[string, string], undefined>,
  'deleteCallEntry' : ActorMethod<[bigint], undefined>,
  'deleteMessage' : ActorMethod<[ConversationId, bigint], undefined>,
  'getCallHistory' : ActorMethod<[], Array<CallLogEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserConversations' : ActorMethod<[], Array<ConversationId>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasConversation' : ActorMethod<[ConversationId], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMessages' : ActorMethod<[ConversationId], Array<Message>>,
  'recordCall' : ActorMethod<
    [[] | [Username], [] | [Username], CallType, bigint, string],
    undefined
  >,
  'removeConversation' : ActorMethod<[ConversationId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchUsers' : ActorMethod<[string], Array<UserProfile>>,
  'sendMessage' : ActorMethod<[MessageRequest], MessageReply>,
  'updateProfile' : ActorMethod<[[] | [string], [] | [string]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];